### ISSUE TITLE
Function key reassignment

### ISSUE THREAD

**Issue by masonticehurst** [ameeno/Dell-E7440-Hackintosh#23]
Hello, I'm new to Hackintosh and I've got macOS Mojave setup on a E7440 almost perfectly so firstly thank you for this guide.

It appears that the functions keys are not mapped in coordination with what the keyboard is designed for (ie. Brightness being Fn+ArrowUp and Fn+ArrowDown). Is there any possibility of including something to remap these keys?

**Comment by ameeno** [comment]
Function keys are presently mapped the same as they would be on an original Mac.

It may be possible to remap them using the voodoops2 controller. You have to appreciate macOS is designed to work with apple based laptops so special keys are hard to map, However there is an app called https://pqrs.org/osx/karabiner/

this app is good for remapping keys, but i just got used to using the apple brightness key locations

**Comment by masonticehurst** [comment]
That is understandable. I did a bit of research on that voodoops2 controller kext along side some ACPI ones and they look promising. I'll report back if I can somehow package a custom configuration for the E7440.

Thanks for the tip on that software, I'll check that out as well if all else fails.

**Comment by ameeno** [comment]
Hello, Based on herves patching guide it is possible via DSDT.aml to map brightness keys to FN + Arrows. try this dsdt.aml file in your clover/acpi/patched folder. 

[DSDT.aml.zip](https://github.com/ameeno/Dell-E7440-Hackintosh/files/3626696/DSDT.aml.zip)

**Comment by masonticehurst** [comment]
Yep, works perfectly. Do you know what lines on the DSDT file allows for this? I can test with other functions. There are a few commented lines referencing "Brightness Controls" but it's unclear which map keys.

**Comment by ameeno** [comment]
Great! Thanks for the feedback.

You could use maciasl and disasemble both the original dsdt and the modified one and compare.

However the dsdt *BRIGHTNESS KEYS* patches *ACPI* directly not necesarily keycodes, So what are you trying to accomplish exactly?

it is not a simple keycode scan & replace to match other keys.

For example if you wish to patch sound, you would patch sound directly.

Honestly the best way to remap keys is to use a helpertool like karibiner otherwise you will be patching a bunch of system internal drivers hehehe :)

**Comment by VGerris** [comment]
That DSDT.aml doesn't work for me for mapping the keys. I'm also interested in having the keys mapped to the keys on the keyboard in blue. Is there any way to do that? Or should I replace the original DSDT.aml from the boot package with this one? I tried that but then sound stops working.
Thanks for the package by the way, works great :)

**Comment by ameeno** [comment]
You can try the DSDT i posted in this thread, it is very beta, and i have
not tested it very much. If it works for you (Like its worked for quite a
few others) i will upstream it :)

**Comment by VGerris** [comment]
hi, the keys work but sound breaks unfortunately. I also wanted to add that it doesn't seem possible to remap the arrow keys + fn with Karabiner, because there is no event in the Event viewer when Fn+up and down are pressed. I currently have Fn+F3 doing brightness down which shows F14 in Karabiner and Fn+Insert for brightness up, that shows F15. Guess patching DSDT is the only way.

**Comment by ameeno** [comment]
Yes brightness keys is linked to api. You must patch dsdt.

Thus pack turns your Dell into a mac pro, it is not dell into mac pro and still use dell hot keys.

The keyboard mapping is equivalent  to a real mbp
